-- ============================================================
-- Seed Data for Development / Testing
-- ============================================================

-- Insert sample hospitals
INSERT INTO public.hospitals (id, name, abbreviation) VALUES
    ('a1b2c3d4-1111-4000-8000-000000000001', 'โรงพยาบาลเกาะคา', 'KOKHA'),
    ('a1b2c3d4-2222-4000-8000-000000000002', 'โรงพยาบาลนางรอง', 'NANGRONG'),
    ('a1b2c3d4-3333-4000-8000-000000000003', 'โรงพยาบาลแม่สอด', 'MAESOT');

-- Insert sample users
INSERT INTO public.users (id, line_uid, display_name, hospital_id, department) VALUES
    ('b1b2c3d4-1111-4000-8000-000000000001', 'U1234567890abcdef01', 'สมชาย ใจดี', 'a1b2c3d4-1111-4000-8000-000000000001', 'ห้องพยาบาล'),
    ('b1b2c3d4-2222-4000-8000-000000000002', 'U1234567890abcdef02', 'สมหญิง รักงาน', 'a1b2c3d4-2222-4000-8000-000000000002', 'ห้องทำงานแพทย์'),
    ('b1b2c3d4-3333-4000-8000-000000000003', 'U1234567890abcdef03', 'วิชัย เทคโน', 'a1b2c3d4-3333-4000-8000-000000000003', 'IT');

-- Insert sample tickets (ticket_no will be auto-generated by trigger!)
INSERT INTO public.tickets (description, module, issue_type, status, reporter_id) VALUES
    ('เครื่องพิมพ์ไม่สามารถพิมพ์ได้', 'ห้องพยาบาล', 'PB', 'Pending', 'b1b2c3d4-1111-4000-8000-000000000001'),
    ('ขอเพิ่มฟีเจอร์ออกรายงานสรุปยา', 'ห้องทำงานแพทย์', 'แนะนำ', 'In Progress', 'b1b2c3d4-2222-4000-8000-000000000002'),
    ('ระบบค้างเมื่อเปิดหน้ารายงาน', 'IT', 'Bug', 'Escalated', 'b1b2c3d4-3333-4000-8000-000000000003');

-- Update the escalated ticket
UPDATE public.tickets 
SET escalated_to = 'Programmer', 
    notes = 'ส่งต่อให้ทีม Programmer ตรวจสอบ performance issue',
    assignee_name = 'จิรายุ ผู้ดูแลระบบ'
WHERE reporter_id = 'b1b2c3d4-3333-4000-8000-000000000003';
